application: super-material-seed-gae
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /material
  static_dir: material


- url: /courses
  script: course_controller.app
  login: required

- url: /courses/.*
  script: course_controller.app
  login: required

- url: /.*
  script: main_controller.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest





